name: changelog

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  changelog:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTION_TOKEN }}

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.ACTION_TOKEN}}

      - name: Merge master to main branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          if ! git show-ref --verify --quiet refs/heads/main; then
            git checkout -b main
          else
            git checkout main
          fi
          git fetch origin master
          git merge origin/master
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{secrets.ACTION_TOKEN}}